export { default as Button } from './button.vue'
export { default as Header } from './Header.vue'
export { default as Footer } from './Footer.vue'
export { default as TextField } from './TextField.vue'
export { default as AddTask } from './AddTask.vue'
export { default as Tasks } from './Tasks.vue'
export { default as Loader } from './Loader.vue'
export { default as Task } from './Task.vue'
export { default as Modal } from "./Modal.vue"